### ISSUE TITLE
emulandice fails when run within EnTK

### ISSUE THREAD

**Issue by bobkopp** [radical-collaboration/facts#101]
```
Traceback (most recent call last):
  File "emulandice_project_AIS.py", line 220, in <module>
    emulandice_project_AIS(args.pipeline_id)
  File "emulandice_project_AIS.py", line 113, in emulandice_project_AIS
    emulandice_dirname = subprocess.run(["bash", emulandice_newinstance, str(nsamps)+"L"], capture_output=True, text=True).stdout.rstrip()
  File "/projects/community/py-data-science-stack/5.1.0/kp807/lib/python3.6/subprocess.py", line 403, in run
    with Popen(*popenargs, **kwargs) as process:
TypeError: __init__() got an unexpected keyword argument 'capture_output'
```

emulandice runs successfully outside of the EnTK framework with a properly set up environment. However, I am not sure how best to set up the environment for running emulandice (which is in R) within the context of EnTK.

**Comment by bobkopp** [comment]
I've recoded the emulandice modules to share code better and to set up the R environment properly using packrat and (on Amarel) the modules from /projects/community/R3.6_lib_workshop where available. The code (which includes scripts to load intel/19.0.3, R/3.6.3-gc563 and gcc/7.3.0-gc563) the Amarel modules runs fine outside of EnTK, but in EnTK fails:

```
Error in dyn.load(file, DLLpath = DLLpath, ...) :
  unable to load shared object '/scratch/rk509/radical.pilot.sandbox/re.session.amarel2.amarel.rutgers.edu.rk509.019305.0007/pilot.0000/task.0010/packrat/lib/x86_64-pc-linux-gnu/3.6.3/vroom/libs/vroom.so':
  /opt/sw/packages/gcc/5.4/lib64/libstdc++.so.6: version `CXXABI_1.3.11' not found (required by /scratch/rk509/radical.pilot.sandbox/re.session.amarel2.amarel.rutgers.edu.rk509.019305.0007/pilot.0000/task.0010/packrat/lib/x86_64-pc-linux-gnu/3.6.3/vroom/libs/vroom.so)
Calls: <Anonymous> ... getNamespace -> loadNamespace -> library.dynam -> dyn.load
```

**Comment by bobkopp** [comment]
Appears to be fixed, without apparently creating any knock on effects, by running 'module purge' before the 'module load' commands.
