### ISSUE TITLE
tlm/oceandynamics fails when run in EnTK

### ISSUE THREAD

**Issue by bobkopp** [radical-collaboration/facts#102]
```
Traceback (most recent call last):
  File "tlm_project_oceandynamics.py", line 309, in <module>
    tlm_project_thermalexpansion(args.seed, args.nsamps, args.pipeline_id)
  File "tlm_project_oceandynamics.py", line 191, in tlm_project_thermalexpansion
    my_data = pickle.load(f)
ValueError: peek of closed file
srun: error: hal0264: task 0: Exited with exit code 1
```

At this point in the code, it is looking for the file ending "tlmfit.pkl", which was produced in the fit stage but not successfully copied over. Will try editing pipeline.yml to see if can be fixed.

**Comment by bobkopp** [comment]
Fixed.
