### ISSUE TITLE
Error when running `runFACTS.py` with complete location file

### ISSUE THREAD

**Issue by jetesdal** [radical-collaboration/facts#164]
I am encountering an error when running `runFACTS.py` using the complete `location.lst` file. The error message is:
```lua
Traceback (most recent call last):
  File "/cache/home/jt1187/ve3/lib64/python3.6/site-packages/radical/entk/appman/appmanager.py", line 427, in run
    self._run_workflow()
  File "/cache/home/jt1187/ve3/lib64/python3.6/site-packages/radical/entk/appman/appmanager.py", line 693, in _run_workflow
    self._rmgr.submit_resource_request()
  File "/cache/home/jt1187/ve3/lib64/python3.6/site-packages/radical/entk/execman/rp/resource_manager.py", line 157, in submit_resource_request
    self._session = rp.Session(uid=self._sid)
  File "/cache/home/jt1187/ve3/lib64/python3.6/site-packages/radical/pilot/session.py", line 94, in __init__
    self._cfg     = ru.Config('radical.pilot.session',  name=name, cfg=cfg)
  File "/cache/home/jt1187/ve3/lib64/python3.6/site-packages/radical/utils/config.py", line 319, in __init__
    if not os.path.isfile(sys_fname):
  File "/usr/lib64/python3.6/genericpath.py", line 30, in isfile
    st = os.stat(path)
KeyboardInterrupt

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "runFACTS.py", line 207, in <module>
    run_experiment(args.edir, args.debug, resourcedir=args.resourcedir, makeshellscript = args.shellscript)
  File "runFACTS.py", line 101, in run_experiment
    amgr.run()
  File "/cache/home/jt1187/ve3/lib64/python3.6/site-packages/radical/entk/appman/appmanager.py", line 439, in run
    raise ree.EnTKError(ex) from ex
radical.entk.exceptions.EnTKError
```

The error occurred during the totaling step of the different workflows. The last bit of lines of the output (before the error) is:
```yaml
submit: ########################################################################
Update: coupling.ssp585.total.facts.total.wf1f.local.workflow.task1 state: FAILED
task task.0053 failed: RuntimeError("task failed")
exit code: 135
Update: coupling.ssp585.total.facts.total.wf1f.local.workflow state: DONE
Update: coupling.ssp585.total.facts.total.wf1f.local state: DONE
Update: coupling.ssp585.total.facts.total.wf4.local.workflow.task1 state: FAILED
task task.0061 failed: RuntimeError("task failed")
exit code: 135
Update: coupling.ssp585.total.facts.total.wf4.local.workflow state: DONE
Update: coupling.ssp585.total.facts.total.wf4.local state: DONE
Update: coupling.ssp585.total.facts.total.wf3e.local.workflow.task1 state: FAILED
task task.0059 failed: RuntimeError("task failed")
exit code: 1
Update: coupling.ssp585.total.facts.total.wf3e.local.workflow state: DONE
Update: coupling.ssp585.total.facts.total.wf3e.local state: DONE
closing session re.session.amarel2.amarel.rutgers.edu.jt1187.019398.0000       \
close pilot manager                                                            \
wait for 1 pilot(s)
              0                                                               ok
                                                                              ok
session lifetime: 2707.1s                                                     ok
close task manager                                                            ok
wait for 1 pilot(s)
              0                                                          timeout
All components terminated
```

I have successfully run the `runFACTS.py` script with a smaller `location.lst` file (10 locations), but I am hoping to get results for all locations for my analysis. I am trying to determine the cause of the error, whether it is due to insufficient memory, exceeding the allotted time for the task or a bug. Any assistance in troubleshooting the issue is appreciated.

Is there a way to examine any log files or outputs from the failed tasks that could provide additional information on the cause of the failure?

## Environment
- Amarel (Linux)
- FACTS version (commit: 43bd25b564c963e8fa41f15178bd07fa02cdd583)

**Comment by andre-merzky** [comment]
```py
task task.0053 failed: RuntimeError("task failed")
exit code: 135
```

This is the interesting part I think.    The tasks run out of memory.  @AlexReedy, @pkjr002 and I are iterating on the memory allocation part and will ping back shortly.

**Comment by AlexReedy** [comment]
Hey @jetesdal yes we're currently working on this! I believe we have narrowed it down to FACTS needing more memory than is allocated by default and @andre-merzky is working on requesting more

**Comment by bobkopp** [comment]
@AlexReedy confirms that code now can run through with nsamps=2000 and nlocations=66190.
