### ISSUE TITLE
`FileNotFoundError` in `ar5k14.rcp85` experiment when running `kopp14/sterodynamics` module

### ISSUE THREAD

**Issue by jetesdal** [radical-collaboration/facts#170]
I am unable to run experiment `ar5k14.rcp85` due to `kopp14/sterodynamics` module failing. I am using the latest version of FACTS (commit: 43bd25b564c963e8fa41f15178bd07fa02cdd583) on Amarel.  Here are the commands I have used to try to run the`ar5k14.rcp85` experiment:

```bash
cd /home/jt1187/facts
mkdir myexperiments
cd myexperiments
mkdir ar5k14.rcp85
cp -r ../experiments/ar5k14.rcp85/config.yml ar5k14.rcp85

# Add location file 
head -n 1030 ../input_files/location.lst > coupling.ssp585/location.lst

# Run experiment
tmux
. ve3/bin/activate
cd /home/jt1187/facts
python3 runFACTS.py myexperiments/ar5k14.rcp85
```

The output indicates that the error comes from a `FileNotFoundError` in the `kopp14/sterodynamics` module:
```
task task.0021 failed: FileNotFoundError(2, 'No such file or directory')
task task.0022 failed: FileNotFoundError(2, 'No such file or directory')
task task.0023 failed: FileNotFoundError(2, 'No such file or directory')
```
See the full screen capture [here](https://youtu.be/0FSj_iZUB34)
[![Screenshot of the terminal](https://www.dropbox.com/s/d5smyweptvpq649/Screen%20Shot%202023-04-03%20at%202.50.08%20PM.png?dl=0)](https://www.dropbox.com/s/mecvp7tr3dnjye4/FACTS%20fail-MPEG-4.mp4?dl=0)

I believe the origin of the all the errors can be traced back to the preprocessing step (`rcp85.k14sterodynamics.kopp14.sterodynamics.preprocess.task1`).
```
Update: ar5k14.rcp85.k14sterodynamics.kopp14.sterodynamics.preprocess.task1 state: FAILED
task task.0020 failed: RuntimeError("task failed")
exit code: 1
```

My guess is that some renaming might cause the preprocessing for the `kopp14/sterodynamics` module to fail as it may look for files with an old naming convention, which in turn leads to the subsequent steps failing as well.
```python
FileNotFoundError: [Errno 2] No such file or directory: '/scratch/jt1187/radical.pilot.sandbox/re.session.amarel1.amarel.rutgers.edu.jt1187.019449.0001/pilot.0000/task.0020/ar5k14.rcp85.k14sterodynamics.kopp14.sterodynamics_ZOS.pkl'
```

This then also leads to the totaling steps failing:
```
Update: ar5k14.rcp85.total.facts.total.ar5.global.workflow.task1 state: FAILED
Update: ar5k14.rcp85.total.facts.total.k14.global.workflow.task1 state: FAILED
Update: ar5k14.rcp85.total.facts.total.k14.local.workflow.task1 state: FAILED
```

I wonder if this is a known issue, or if there might be something amiss with my settings. I would greatly appreciate any advice on how to tackle this situation.

**Comment by bobkopp** [comment]
Not a known issue. Agree this probably arose from renaming and module cleanup, with an inadequate check since this is a legacy module not employed in the AR6 configuration of FACTS nor with a future in a set up focused on probabilistic projections with consistency between GSAT, OHC and DSL (since K14 is not temperature or OHC driven)

**Comment by jetesdal** [comment]
Hi @AlexReedy. Here is what I can see in `~/facts/modules/kopp14/sterodynamics/`. Let me know if that is what you are looking for.

```
$ ls -1 kopp14_*.py
kopp14_fit_oceandynamics.py
kopp14_postprocess_oceandynamics.py
kopp14_preprocess_oceandynamics.py
kopp14_project_oceandynamics.py
```

```
$ cat pipeline.yml | grep script
    script: "kopp14_preprocess_oceandynamics.py"
    script: "kopp14_fit_oceandynamics.py"
    script: "kopp14_project_oceandynamics.py"
    script: "kopp14_postprocess_oceandynamics.py"
```

**Comment by bobkopp** [comment]
This looks like an issue with the data file, not the scripts.

**Comment by jetesdal** [comment]
I've run a test with `kopp14.sterodynamics` using the `--shellscript` flag (see [here](https://fact-sealevel.readthedocs.io/en/latest/quickstart.html#testing-a-module-with-a-shell-script) in the FACTS documentation). You can find the `test.sh` script [here](https://gist.github.com/jetesdal/77a49a22672d9238c7be244b02ad2eef).

I was able to run the shell script and produce the desired output:
> kopp14.sterodynamics.onemodule.kopp14.sterodynamics_globalsl.nc  kopp14.sterodynamics.onemodule.kopp14.sterodynamics_localsl.nc

The test experiment folder for `kopp14.sterodynamics` is
`/home/jt1187/facts/test/kopp14.sterodynamics`

In `/home/jt1187/facts/`, I ran
```bash
python runFACTS.py --shellscript test/kopp14.sterodynamics > test.sh
```
You can find the output and working directory on Amarel:
`/scratch/jt1187/test.1680744106`

Stout is saved here:
```
/home/jt1187/facts/test/kopp14.sterodynamics/test.out
/home/jt1187/facts/test/kopp14.sterodynamics/test.err
```

It does not look like we get an error when running the module via the shell script. `test.err` only includes some warnings:
```
cat /home/jt1187/facts/test/kopp14.sterodynamics/test.err
```
> kopp14_fit_oceandynamics.py:183: RuntimeWarning: Mean of empty slice
>   ext_num = sZOS[year_2099_idx,:,:] - np.nanmean(sZOS[year_2099_idx,:,:], axis=0)
> kopp14_fit_oceandynamics.py:200: RuntimeWarning: Mean of empty slice
>   OceanDynMean = np.nanmean(sZOS, axis=1) * 1000
> /cache/home/jt1187/ve3/lib64/python3.6/site-packages/numpy/lib/nanfunctions.py:1665: RuntimeWarning: Degrees of freedom <= 0 for slice.
>   keepdims=keepdims)
> kopp14_fit_oceandynamics.py:213: RuntimeWarning: Mean of empty slice
>   zos_demean = sZOS - np.nanmean(sZOS, axis=1)[:,np.newaxis,:]
> kopp14_fit_oceandynamics.py:217: RuntimeWarning: invalid value encountered in true_divide
>   OceanDynTECorr = corr_num / corr_denom

So that tells me that I can successfully run the module by itself but it fails when using it in the experiment setup using the RADICAL tools (EnTK). I am unsure where EnTK causes it to fail. Maybe in the file transfer?

**Comment by jetesdal** [comment]
Quick update: I have repeated the test run with a full list of locations in the`location.lst` file and I can now reproduce the FileNotFoundError.

```batch
$ cat test.err 
```
> Traceback (most recent call last):
>   File "kopp14_preprocess_oceandynamics.py", line 185, in <module>
>     kopp14_preprocess_oceandynamics(args.scenario, args.zostoga_model_dir, args.zos_model_dir, not args.no_drift_corr, args.baseyear, args.pyear_start, args.pyear_end, args.pyear_step, args.locationfile, args.pipeline_id)
>   File "kopp14_preprocess_oceandynamics.py", line 121, in kopp14_preprocess_oceandynamics
>     sZOS = np.apply_along_axis(nanSmooth, axis=0, arr=ZOS, w=smoothwin)
>   File "<__array_function__ internals>", line 6, in apply_along_axis
>   File "/cache/home/jt1187/ve3/lib64/python3.6/site-packages/numpy/lib/shape_base.py", line 402, in apply_along_axis
>     buff[ind] = asanyarray(func1d(inarr_view[ind], *args, **kwargs))
>   File "kopp14_preprocess_oceandynamics.py", line 118, in nanSmooth
>     temp[idx] = Smooth(x[idx], w)
>   File "/scratch/jt1187/test.1680751835/kopp14.sterodynamics.onemodule.kopp14.sterodynamics/Smooth.py", line 19, in Smooth
>     start = np.cumsum(x[:w-1])[::2]/r
> ValueError: operands could not be broadcast together with shapes (4,) (9,) 
> Traceback (most recent call last):
>   File "kopp14_fit_oceandynamics.py", line 282, in <module>
>     kopp14_fit_oceandynamics(args.pipeline_id)
>   File "kopp14_fit_oceandynamics.py", line 60, in kopp14_fit_oceandynamics
>     my_zos = pickle.load(f)
> ValueError: peek of closed file
> Traceback (most recent call last):
>   File "kopp14_project_oceandynamics.py", line 148, in <module>
>     kopp14_project_oceandynamics(args.nsamps, args.seed, args.pipeline_id)
>   File "kopp14_project_oceandynamics.py", line 52, in kopp14_project_oceandynamics
>     my_fit = pickle.load(f)
> ValueError: peek of closed file
> cp: cannot stat ‘kopp14.sterodynamics.onemodule.kopp14.sterodynamics_globalsl.nc’: No such file or directory
> Traceback (most recent call last):
>   File "kopp14_postprocess_oceandynamics.py", line 205, in <module>
>     kopp14_postprocess_oceandynamics(args.nsamps, args.seed, args.pipeline_id)
>   File "kopp14_postprocess_oceandynamics.py", line 50, in kopp14_postprocess_oceandynamics
>     f = open(infile, 'rb')
> FileNotFoundError: [Errno 2] No such file or directory: 'kopp14.sterodynamics.onemodule.kopp14.sterodynamics_ZOS.pkl'
> cp: cannot stat ‘kopp14.sterodynamics.onemodule.kopp14.sterodynamics_localsl.nc’: No such file or directory


So it looks like that the added location causes `kopp14_preprocess_oceandynamics.py` to fail and not produce the input files for the subsequent step. There seems to be a mismatch in the shapes of the operands during the smoothing process in `kopp14_preprocess_oceandynamics.py`
```
ValueError: operands could not be broadcast together with shapes (4,) (9,)  
```

I am trying to figure out what would cause the mismatch in shapes just by having more locations.

**Comment by bobkopp** [comment]
Looks like the code is expecting dimensions of (time, model, location), but the (4,9) suggests dimensions of (scenario, time) to me. Not sure why.
________________________________

**Comment by bobkopp** [comment]
Was this issue diagnosed? @jetesdal @AlexReedy

**Comment by jetesdal** [comment]
I have not yet found the underlying cause of the error. I can coordinate with @AlexReedy to further dig into the code to identify the issue. Has anyone else encountered the error?

**Comment by AlexReedy** [comment]
Hey @jetesdal what times do you have available to look at this?

**Comment by bobkopp** [comment]
I do note that the part of the code here that appears to be breaking appears identical between `tlm/sterodynamics` (which is used regularly) and `kopp14/sterodynamics` which (is rarely used). Thus my suspicion is that the error has something to do with either the `kopp14/sterodynamics` input files or the way they are read in by `IncludeModels`, and how this differs from the `tlm/sterodynamics` models and how they are read in by `IncludeCMIP6ZOSModels`.

**Comment by AlexReedy** [comment]
for last 4 days have been running into issues with getting ar5k experiments running after amarel maintenance update so this is ongoing

**Comment by AlexReedy** [comment]
I have been diagnosing this and have something that may be helpful, I don't really know what this script is trying to do but I can at least explain what I'm seeing 
The issue as we know arises in Smooth.py line 19 

`start = np.cumsum(x[:w-1])[::2]/r`

so r is the smoothing window (w = 19 years) in two year steps 

`r = np.arange(1,w-1,2, dtype="double")`

which gives an array 
[1,3,5,7,9,11,13,15,17] (length 9)
As x is iterated through and that np.cumsum(x[:w-1])[::2] is calculated it's only going from idx=0 to w-1 which should also be 0-18 in steps of two so 9, but there is a point where the length of x changes during this smoothing and there are only 7 array elements. So it still performs
`start = np.cumsum(x[:w-1])[::2]/r`
but it only pulls the elements up 7 so 
np.cumsum(x[:w-1])[::2] winds up only equaling 4. 

This gives the broadcasting error where it's trying to divide an array of length 4 by that of 9
I'm still looking into why the length changes and why the locations have anything to do with it.

**Comment by bobkopp** [comment]
@AlexReedy Have you compared the difference in the shape of inputted data between the two different modules?

**Comment by jetesdal** [comment]
When I replaced `np.apply_along_axis()` with a nested loop I could identify that the error occurs for a specific model and location 
```
 model = 'bcc-csm1-1' and location='KUNGSHOLMSFORT'
 ```

For some reason the `zos` time series in that case only includes a handful of points and causes the smoothing function to fail with the broadcasting error. A quick fix is implemented here:
 loopshttps://github.com/jetesdal/facts/commit/85630bd73880d04fbbd1e8579f109fd9a1fd8a15
where smoothing is only done when number of `zos` values are larger than the smoothing window. This lets me successfully run the kopp14 sterodynamics module for all tide gauge locations, but it might be better to ensure that this particular model is removed at the particular location.

**Comment by kemccusker** [comment]
@bobkopp @jetesdal Any idea if this fix still needs to be merged? It seems that way?
