### ISSUE TITLE
Remote run from docker container fails

### ISSUE THREAD

**Issue by bobkopp** [radical-collaboration/facts#243]
This is using the new, Mongo-free version of EnTK. Cannot easily run with the old version, as I'm not sure how to install it via pip.

```
root@localhost:/opt/facts# python3 runFACTS.py --global_options '{"rcfg-name": "
amarel"}' experiments/dummy
EnTK session: re.session.ea2cf652-6e87-11ee-ad9c-0242ac110002
Creating AppManager
Setting up ZMQ queues                                                         ok
AppManager initialized                                                        ok
Validating and assigning resource manager                                     ok
****** STEP: sealevel_step ******
Setting up ZMQ queues                                                        n/a
new session: [re.session.ea2cf652-6e87-11ee-ad9c-0242ac110002]                 \
zmq proxy  : [tcp://172.17.0.2:10001]                                         ok
create pilot manager                                                          ok
submit 1 pilot(s)
        pilot.0000   rutgers.amarel           12 cores       0 gpus           ok
closing session re.session.ea2cf652-6e87-11ee-ad9c-0242ac110002                \
close pilot manager                                                            \
wait for 1 pilot(s)
              0                                                               ok
                                                                              ok
session lifetime: 11.1s                                                       ok
All components terminated
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/radical/entk/appman/appmanager.py", line 459, in run
    self._rmgr.submit_resource_request()
  File "/usr/local/lib/python3.8/dist-packages/radical/entk/execman/rp/resource_manager.py", line 225, in submit_resource_request
    self._pilot.wait([rp.PMGR_ACTIVE, rp.DONE, rp.FAILED, rp.CANCELED])
  File "/usr/local/lib/python3.8/dist-packages/radical/pilot/pilot.py", line 585, in wait
    time.sleep(0.1)
KeyboardInterrupt

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "runFACTS.py", line 193, in <module>
    run_experiment(args.edir, args.debug, args.alt_id, resourcedir=args.resourcedir, makeshellscript = args.shellscript, globalopts = args.global_options)
  File "runFACTS.py", line 86, in run_experiment
    amgr.run()
  File "/usr/local/lib/python3.8/dist-packages/radical/entk/appman/appmanager.py", line 485, in run
    raise EnTKError(ex) from ex
radical.entk.exceptions.EnTKError
```

No actual keyboard interrupt is provided, and a manual `ssh [userid]@amarel.rutgers.edu` works fine from within the container. 

Running on localhost has no problem:

```
root@localhost:/opt/facts# python3 runFACTS.py experiments/dummy
EnTK session: re.session.5406a0aa-6e88-11ee-9b90-0242ac110002
Creating AppManager
Setting up ZMQ queues                                                         ok
AppManager initialized                                                        ok
Validating and assigning resource manager                                     ok
****** STEP: sealevel_step ******
Setting up ZMQ queues                                                        n/a
new session: [re.session.5406a0aa-6e88-11ee-9b90-0242ac110002]                 \
zmq proxy  : [tcp://172.17.0.2:10001]                                         ok
create pilot manager                                                          ok
submit 1 pilot(s)
        pilot.0000   local.localhost           2 cores       0 gpus           ok
All components created
Update: dummy.dummy.facts.dummy state: SCHEDULING
Update: dummy.dummy.facts.dummy.preprocess state: SCHEDULING
Update: dummy.dummy.facts.dummy.preprocess.task1 state: SCHEDULING
Update: dummy.dummy.facts.dummy.preprocess.task1 state: SCHEDULED
Update: dummy.dummy.facts.dummy.preprocess state: SCHEDULED
create task manager                                                           ok
submit: ########################################################################
Update: dummy.dummy.facts.dummy.preprocess.task1 state: SUBMITTING
Update: dummy.dummy.facts.dummy.preprocess.task1 state: DONE
Update: dummy.dummy.facts.dummy.preprocess state: DONE
Update: dummy.dummy.facts.dummy state: DONE
close task manager                                                            ok
closing session re.session.5406a0aa-6e88-11ee-9b90-0242ac110002                \
close pilot manager                                                            \
wait for 1 pilot(s)
              0                                                               ok
                                                                              ok
session lifetime: 71.4s                                                       ok
All components terminated
```

**Comment by bobkopp** [comment]
This error also occurs with the MongoDB-based version of RCT (1.37.0), so likely has to do with the docker configuration; the tie to the MongoDB removal is a red herring.

```
(ve3) root@localhost:/opt/facts# python3 runFACTS.py --global_options '{"rcfg-name": "amarel"}' experiments/dummy
EnTK session: re.session.2a7c958a-6ef8-11ee-ae76-0242ac110002
Creating AppManager
Setting up ZMQ queues                                                         ok
AppManager initialized                                                        ok
Validating and assigning resource manager                                     ok
****** STEP: sealevel_step ******
Setting up ZMQ queues                                                        n/a
new session: [re.session.2a7c958a-6ef8-11ee-ae76-0242ac110002]                 \
database   : [mongodb://localhost:27017/facts]                                ok
create pilot manager                                                          ok
submit 1 pilot(s)
        pilot.0000   rutgers.amarel            2 cores       0 gpus           ok
closing session re.session.2a7c958a-6ef8-11ee-ae76-0242ac110002                \
close pilot manager                                                            \
wait for 1 pilot(s)
              0                                                               ok
                                                                              ok
session lifetime: 11.6s                                                       ok
All components terminated
Traceback (most recent call last):
  File "/ve3/lib/python3.8/site-packages/radical/entk/appman/appmanager.py", line 459, in run
    self._rmgr.submit_resource_request()
  File "/ve3/lib/python3.8/site-packages/radical/entk/execman/rp/resource_manager.py", line 225, in submit_resource_request
    self._pilot.wait([rp.PMGR_ACTIVE, rp.DONE, rp.FAILED, rp.CANCELED])
  File "/ve3/lib/python3.8/site-packages/radical/pilot/pilot.py", line 552, in wait
    time.sleep(0.1)
KeyboardInterrupt

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "runFACTS.py", line 221, in <module>
    run_experiment(args.edir, args.debug, args.alt_id, resourcedir=args.resourcedir, makeshellscript = args.shellscript, globalopts = args.global_options)
  File "runFACTS.py", line 114, in run_experiment
    amgr.run()
  File "/ve3/lib/python3.8/site-packages/radical/entk/appman/appmanager.py", line 485, in run
    raise EnTKError(ex) from ex
radical.entk.exceptions.EnTKError
```

**Comment by andre-merzky** [comment]
Bob, would you mind doing the following:

```sh
export RADICAL_LOG_LVL=DEBUG
export RADICAL_DEBUG=TRUE
export RADICAL_DEBUG_HELPER=TRUE
export RADICAL_UTILS_HEARTBEAT_LOG_LVL=ERROR
```
 and then run the application again.  Please attach the resulting session sandbox to this ticket.
 
 Thank you!

**Comment by bobkopp** [comment]
```
python3 runFACTS.py experiments/dummy
EnTK session: re.session.dac899fc-729f-11ee-b9ca-0242ac110002
Creating AppManager
Setting up ZMQ queues                                                         ok
AppManager initialized                                                        ok
Validating and assigning resource manager                                     ok
****** STEP: sealevel_step ******
Setting up ZMQ queues                                                        n/a
new session: [re.session.dac899fc-729f-11ee-b9ca-0242ac110002]                 \
zmq proxy  : [tcp://172.17.0.2:10001]                                         ok
create pilot manager                                                          ok
submit 1 pilot(s)
        pilot.0000   rutgers.amarel            2 cores       0 gpus           ok
closing session re.session.dac899fc-729f-11ee-b9ca-0242ac110002                \
close pilot manager                                                            \
wait for 1 pilot(s)
              0                                                               ok
                                                                              ok
session lifetime: 11.0s                                                       ok
All components terminated
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/radical/entk/appman/appmanager.py", line 459, in run
    self._rmgr.submit_resource_request()
  File "/usr/local/lib/python3.8/dist-packages/radical/entk/execman/rp/resource_manager.py", line 225, in submit_resource_request
    self._pilot.wait([rp.PMGR_ACTIVE, rp.DONE, rp.FAILED, rp.CANCELED])
  File "/usr/local/lib/python3.8/dist-packages/radical/pilot/pilot.py", line 585, in wait
    time.sleep(0.1)
KeyboardInterrupt

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "runFACTS.py", line 221, in <module>
    run_experiment(args.edir, args.debug, args.alt_id, resourcedir=args.resourcedir, makeshellscript = args.shellscript, globalopts = args.global_options)
  File "runFACTS.py", line 114, in run_experiment
    amgr.run()
  File "/usr/local/lib/python3.8/dist-packages/radical/entk/appman/appmanager.py", line 485, in run
    raise EnTKError(ex) from ex
radical.entk.exceptions.EnTKError
```

**Comment by bobkopp** [comment]
Ok, this sounds like a documentation issue rather than a docker issue.

**Comment by bobkopp** [comment]
See https://github.com/radical-collaboration/facts/issues/246
