### ISSUE TITLE
MongoDB down?

### ISSUE THREAD

**Issue by ggg121** [radical-collaboration/facts#30]
I’m trying to run a FACTS workflow, but it fails trying to create the session.  Is there something wrong with the server running mongodb?  Error is below:

```
(facts_env) greg@greg-VirtualBox:~/research/facts/re.session.greg-VirtualBox.greg.018514.0001$ more radical.entk.resource_manager.0000.log 
1599679333.178 : radical.entk.resource_manager.0000 : 10835 : 140535638288192 : ERROR    : Resource request submission failed
Traceback (most recent call last):
  File "/home/greg/facts_env/lib/python3.8/site-packages/radical/pilot/session.py", line 177, in _initialize_primary
    self._dbs = DBSession(sid=self.uid, dburl=dburl,
  File "/home/greg/facts_env/lib/python3.8/site-packages/radical/pilot/db/database.py", line 50, in __init__
    self._mongo, self._db, _, _, _ = ru.mongodb_connect(str(dburl))
  File "/home/greg/facts_env/lib/python3.8/site-packages/radical/utils/misc.py", line 120, in mongodb_connect
    db.authenticate(user, pwd)
  File "/home/greg/facts_env/lib/python3.8/site-packages/pymongo/database.py", line 1492, in authenticate
    self.client._cache_credentials(
  File "/home/greg/facts_env/lib/python3.8/site-packages/pymongo/mongo_client.py", line 775, in _cache_credentials
    server = self._get_topology().select_server(
  File "/home/greg/facts_env/lib/python3.8/site-packages/pymongo/topology.py", line 241, in select_server
    return random.choice(self.select_servers(selector,
  File "/home/greg/facts_env/lib/python3.8/site-packages/pymongo/topology.py", line 199, in select_servers
    server_descriptions = self._select_servers_loop(
  File "/home/greg/facts_env/lib/python3.8/site-packages/pymongo/topology.py", line 215, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: 129.114.17.185:27017: timed out, Timeout: 30s, Topology Description: <TopologyDescription id: 5f592b47b9c5ff5c7873
11a6, topology_type: Single, servers: [<ServerDescription ('129.114.17.185', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('129.114.17.185:2701
7: timed out')>]>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/greg/facts_env/lib/python3.8/site-packages/radical/entk/execman/rp/resource_manager.py", line 147, in _submit_resource_request
    self._session = rp.Session(uid=self._sid)
  File "/home/greg/facts_env/lib/python3.8/site-packages/radical/pilot/session.py", line 148, in __init__
    self._initialize_primary(dburl)
  File "/home/greg/facts_env/lib/python3.8/site-packages/radical/pilot/session.py", line 192, in _initialize_primary
    raise RuntimeError ('session create failed [%s]' %
RuntimeError: session create failed [mongodb://facts:****@129.114.17.185/facts]
```

**Comment by andre-merzky** [comment]
Hi Greg, Jetstream @ Tacc experiences system problems right now, and our VMs are affected.  We hope this gets resolved soon...

**Comment by ggg121** [comment]
Hi Andre,

Thank you for the information.  I did see the emails about Jetsteam, but I didn't realize the VM with MongoDB was tied to it.  Fingers crossed it gets resolved soon!

**Comment by ggg121** [comment]
It appears things are back up and running again!  Thank you @andre-merzky and @mturilli for your help.
