### ISSUE TITLE
FACTS stopped working on Amarel

### ISSUE THREAD

**Issue by jetesdal** [radical-collaboration/facts#351]
After months of successfully running FACTS on Amarel, I am now encountering a generic error when attempting to run a FACTS experiment:
```
EnTK session: re.session.hal0265.amarel.rutgers.edu.jt1187.020076.0002
Creating AppManager
Setting up ZMQ queues                                                         ok
AppManager initialized                                                        ok
Validating and assigning resource manager                                     ok
Setting up ZMQ queues                                                        n/a
All components terminated
Traceback (most recent call last):
  File "/cache/home/jt1187/ve3/lib/python3.9/site-packages/radical/entk/appman/appmanager.py", line 459, in run
    self._rmgr.submit_resource_request()
  File "/cache/home/jt1187/ve3/lib/python3.9/site-packages/radical/entk/execman/rp/resource_manager.py", line 225, in submit_resource_request
    self._pilot.wait([rp.PMGR_ACTIVE, rp.DONE, rp.FAILED, rp.CANCELED])
  File "/cache/home/jt1187/ve3/lib/python3.9/site-packages/radical/pilot/pilot.py", line 589, in wait
    time.sleep(0.1)
KeyboardInterrupt

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/cache/home/jt1187/facts/./runFACTS.py", line 193, in <module>
    run_experiment(args.edir, args.debug, args.alt_id, resourcedir=args.resourcedir, makeshellscript = args.shellscript, globalopts = args.global_options)
  File "/cache/home/jt1187/facts/./runFACTS.py", line 86, in run_experiment
    amgr.run()
  File "/cache/home/jt1187/ve3/lib/python3.9/site-packages/radical/entk/appman/appmanager.py", line 485, in run
    raise EnTKError(ex) from ex
radical.entk.exceptions.EnTKError
```

Again, FACTS was working fine previously, and no changes were made to the FACTS or Python environment on my side. @AymenFJA pointed out in issue #348 that the error above is due to a dependency issue between urllib3 v2 and OpenSSL. It is still not clear to me why suddenly there is this dependency issue when I have not changed anything in my Python environment or the version of RADICAL Cybertools (RCT). The following is identical between the previous successful run (on Dec 11) and the failed run (since Dec 16):

```
python               : /cache/home/jt1187/ve3/bin/python3
  pythonpath           : 
  version              : 3.9.19
  virtualenv           : /cache/home/jt1187/ve3

  radical.entk         : 1.60.0
  radical.gtod         : 1.60.0
  radical.pilot        : 1.60.0
  radical.utils        : 1.60.0
  ```
  
So I though that I am just using version 1.60 for all radical packages. However, one thing I noticed is that the RCT package versions have changed in the sandbox (see packages installed in `radical.pilot.sandbox/re.session.*/pilot.0000/rp_install/`. Specifically:
	•	Working Environment: Radical versions radical.pilot==1.83.0, radical.utils==1.84.0, and radical.gtod==1.81.0.
	•	Failed Environment: Radical versions radical.pilot==1.90.0, radical.utils==1.90.0, and radical.gtod==1.90.0.

It seems that when FACTS runs in the sandbox it automatically pulls and uses the latest versions of the Radical libraries, which introduces the failure. This behavior occurred despite no intentional changes to my environment or dependencies. Given that FACTS was previously functioning perfectly with the older versions, I suspect that the newer versions of RCT libraries may be introducing changes or dependencies (e.g., urllib3 and OpenSSL compatibility) that cause the failure.

Can you confirm whether the newer versions of the RCT are required for FACTS to function? If not, is it possible to use the older versions explicitly in the FACTS environment to resolve this issue and ensure FACTS can still be used on Amarel?

**Comment by AymenFJA** [comment]
Hello again @jetesdal, Yes. This is a mismatch between your `client` and `agent` RCT stack. You can update your stack to the latest RCT env, as it has a lot of performance and stability improvements. In case you want to use your current stack (`1.6x`) you can instruct RCT to use your existing env (and ultimately the RCT stack within that env) as follows:

from your home dir execute the following:
```
mkdir -p ~/.radical/pilot/configs
cat > ~/.radical/pilot/configs/resource_rutgers.json <<EOF
{
    "amarel": {"virtenv_mode": "local"}
}
EOF
```

This will enforce the usage of your local `env` in your case `/cache/home/jt1187/ve3`.

**Comment by andre-merzky** [comment]
I think you also should set `rp_version` in that config:

```
mkdir -p ~/.radical/pilot/configs
cat > ~/.radical/pilot/configs/resource_rutgers.json <<EOF
{
    "amarel": {
        "virtenv_mode": "local"
        "rp_version": "installed"
    }
}
EOF
```

**Comment by jetesdal** [comment]
Thank you @AymenFJA  and @andre-merzky for your guidance on setting up `resource_rutgers.json`! That did the trick. I am now able to run my FACTS experiment on Amarel without the dependency issues.

**Comment by andre-merzky** [comment]
I am glad this got resolved, @jetesdal.  Don't hesitate to reach out if anything else comes up - Amarel is a somewhat special machine as it's configuration changes from time to time.   This is sometimes difficult to proactively catch on our side, so thanks for letting us know about the issue!

**Comment by jetesdal** [comment]
Hi @andre-merzky, it seems I was celebrating too soon. The initial dependency error is resolved, but now I am encountering issues with package versions when running a standard FACTS experiment. Specifically, there are numerous failures due to old numpy code in FACTS, e.g.,:
```
AttributeError: `np.Inf` was removed in the NumPy 2.0 release. Use `np.inf` instead.
AttributeError: `np.NINF` was removed in the NumPy 2.0 release. Use `-np.inf` instead.
AttributeError: `np.PINF` was removed in the NumPy 2.0 release. Use `np.inf` instead.
```

I assume the more recent version of numpy (Version 2.0.2) in my local environment is causing the errors. The `rp_install` folder does not include numpy, so I am not sure what version was used. I assume it installed an older version of numpy such that the `AttributeError` did not come up? What would you suggest as the best way forward? Is there a way to keep using the default method and have `rp_install` setup a new Python environment with the right versions for FACTS but force the RCT stack to be <1.90?

I think the dependency issue with `urllib3 v2` only happens with the latest version of RCT and I don't know if I have any control on the OpenSSL version available on Amarel.

**Comment by jetesdal** [comment]
UPDATE: This was fixed in #342, but `np.Inf` is still lingering in [extremesealevel/pointsoverthreshold](modules/extremesealevel/pointsoverthreshold):
https://github.com/radical-collaboration/facts/blob/7f7b0cfedafc46f5ae1204134e6f080f061520d5/modules/extremesealevel/pointsoverthreshold/extremesealevel_pointsoverthreshold_fit.py#L107

I'm now testing without `esl_step`

**Comment by andre-merzky** [comment]
> I assume the more recent version of numpy (Version 2.0.2) in my local environment is causing the errors

This.  With the config change of `virtenv_mode=local`, the pilot will use your local virtualenv.  Is it possible to install the numpy version in that local virtualenv that the pilot needs?

@AymenFJA : you know the code better than I do I think - can you please check if the task's `named_env` should be set to `rp` maybe, to better reflect the client env?

**Comment by jetesdal** [comment]
Ok, I am able complete a standard FACTS experiment on Amarel without any failures  using `virtenv_mode=local`, except for the `esl_step`. This step fails due to deprecated numpy function `np.Inf`, which should be replace I think (see #352) such that we don't rely on using an old version for numpy.

**Comment by AymenFJA** [comment]
Hey @jetesdal, besides the `deprecated numpy function` (unrelated to RCT), do you still have an issue running your code with RCT?

**Comment by jetesdal** [comment]
Hi @AymenFJA, the issue has been resolved. I am able to run FACTS again, so we can close this issue. Note that I opened #352 to flag the deprecated numpy function in the `extremesealevel` module code. Thanks!

**Comment by AymenFJA** [comment]
Thanks @jetesdal. 

Resolved, closing.
