### ISSUE TITLE
Test script for module ipccar6/larmipicesheet does not complete

### ISSUE THREAD

**Issue by bobkopp** [radical-collaboration/facts#56]

**Comment by bobkopp** [comment]
Error in the project script:

```
python ipccar6_project_larmipicesheet_dev.py --pipeline_id icesheets-ipccar6-larmipicesheet-ssp585 --nsamps 20000 --seed 4321 --crateyear_start 2080 --crateyear_end 2100

Traceback (most recent call last):
  File "ipccar6_project_larmipicesheet_dev.py", line 393, in <module>
    ipccar6_project_larmipicesheet(args.nsamps, args.pipeline_id, args.crateyear_start, args.crateyear_end, args.replace, args.seed)
  File "ipccar6_project_larmipicesheet_dev.py", line 67, in ipccar6_project_larmipicesheet
    (nmodels, nsamples, nyears) = eais_samples.shape
ValueError: not enough values to unpack (expected 3, got 1)
```

The problem seems to arise earlier; both icesheets-ipccar6-larmipicesheet-ssp585_data.pkl and icesheets-ipccar6-larmipicesheet-ssp585_fit.pkl are <1K in size. This seems possible for the fit file, which should contain only 

```
        output = {'dant': dant, 'dgreen': dgreen, 'fgreendyn': fgreendyn, 'mSLEoGt': mSLEoGt, \
                                'dtgreen': dtgreen, 'fnlogsd': fnlogsd, 'febound': febound, 'pcoK': pcoK, \
                                'KoKg': KoKg, 'smax': smax, 'gdyn_finalrange': gdyn_finalrange, \
                                'adyn_finalrange': adyn_finalrange, 'adyn_startratemean': adyn_startratemean, \
                                'adyn_startratepm': adyn_startratepm}

```

but icesheets-ipccar6-larmipicesheet-ssp585_data.pkl should contain the samples aggregated from the LARMIP netcdf output files. It's implausible that this is possible in <1K, and indeed if I step through the commands for just one NC file and only EAIS, I get a 1.6 MB pickle file. So the preprocessing script must be having trouble finding the data files.
