### ISSUE TITLE
ar5/glacierscmip6, ar5/glaciersfair, ar5/thermalexpansion test scripts fail

### ISSUE THREAD

**Issue by bobkopp** [radical-collaboration/facts#61]
```
Traceback (most recent call last):
  File "ar5_project_glacierscmip6.py", line 244, in <module>
    ar5_project_glacierscmip6(args.seed, args.pyear_start, args.pyear_end, args.pyear_step, args.nmsamps, args.ntsamps, args.nsamps, args.pipeline_id)
  File "ar5_project_glacierscmip6.py", line 167, in ar5_project_glacierscmip6
    year_var[:] = targyears
  File "src/netCDF4/_netCDF4.pyx", line 4903, in netCDF4._netCDF4.Variable.__setitem__
  File "/home/rk509/.conda/envs/conda-entk/lib/python3.7/site-packages/netCDF4/utils.py", line 356, in _StartCountStride
    datashape = broadcasted_shape(shape, datashape)
  File "/home/rk509/.conda/envs/conda-entk/lib/python3.7/site-packages/netCDF4/utils.py", line 964, in broadcasted_shape
    return np.broadcast(a, b).shape
ValueError: shape mismatch: objects cannot be broadcast to a single shape
```

**Comment by bobkopp** [comment]
This seems to only arise if PYEAR_END>2100.
