### ISSUE TITLE
kopp14/oceandynamics test script fails

### ISSUE THREAD

**Issue by bobkopp** [radical-collaboration/facts#62]
```
Traceback (most recent call last):
  File "kopp14_preprocess_oceandynamics.py", line 184, in <module>
    kopp14_preprocess_oceandynamics(args.scenario, args.zostoga_model_dir, args.zos_model_dir, not args.no_drift_corr, args.baseyear, args.pyear_start, args.pyear_end, args.pyear_step, args.locationfile, args.pipeline_id)
  File "kopp14_preprocess_oceandynamics.py", line 120, in kopp14_preprocess_oceandynamics
    sZOS = np.apply_along_axis(nanSmooth, axis=0, arr=ZOS, w=smoothwin)
  File "<__array_function__ internals>", line 6, in apply_along_axis
  File "/home/rk509/.conda/envs/conda-entk/lib/python3.7/site-packages/numpy/lib/shape_base.py", line 402, in apply_along_axis
    buff[ind] = asanyarray(func1d(inarr_view[ind], *args, **kwargs))
  File "kopp14_preprocess_oceandynamics.py", line 117, in nanSmooth
    temp[idx] = Smooth(x[idx], w)
ValueError: shape mismatch: value array of shape (37,) could not be broadcast to indexing result of shape (1,)
```

**Comment by bobkopp** [comment]
This was choking on zos data that, for some reason, had a very limited number of non-NaN entries. Couldn't figure out why, but now fixed.
