### ISSUE TITLE
Configure EnTK on Amarel

### ISSUE THREAD

**Issue by bobkopp** [radical-collaboration/facts#86]

**Comment by bobkopp** [comment]
@andre-merzky @mturilli I'm just a dumb scientist and haven't worked with MongoDB before. I'm trying to get EnTK working on Amarel using both the localhost and amarel resource configurations. I have rabbitmq-server -detachted running on the compute node, and with both configurations get an "OK" for Setting Up the RabbitMQ System.

 In both case, I get failures of the form

```
Traceback (most recent call last):
  File "/home/rk509/.conda/envs/conda-entk/lib/python3.7/site-packages/radical/entk/execman/rp/resource_manager.py", line 157, in submit_resource_request
    self._session = rp.Session(uid=self._sid)
  File "/home/rk509/.conda/envs/conda-entk/lib/python3.7/site-packages/radical/pilot/session.py", line 154, in __init__
    self._initialize_primary(dburl)
  File "/home/rk509/.conda/envs/conda-entk/lib/python3.7/site-packages/radical/pilot/session.py", line 168, in _initialize_primary
    if not dburl: raise RuntimeError("no db URL (set RADICAL_PILOT_DBURL)")
RuntimeError: no db URL (set RADICAL_PILOT_DBURL)
```

There's some basic EnTK setup issue that I'm missing here, and isn't described in the EnTK documentation. Please help!

**Comment by andre-merzky** [comment]
Hi @bobkopp - the following procedure on the **login node** should result in a workable deployment:
```sh
$ git clone git@github.com:radical-collaboration/facts.git
$ cd facts
$ git checkout fix/workflow_assignment

$ python3 -m venv ve3
$ . ve3/bin/activate
$ pip install --upgrade setuptools pip wheel
$ pip install radical.entk
$ pip install numpy scipy netCDF4 pyyaml matplotlib h5py yq

$ mkdir test
$ cp -r experiments/temp_exp/* test
$ vim test/config.yml
  -> replace 'localhost' with 'amarel'
$ python3 runFACTS.py test
```

Alas, some tasks fail because of missing input files, and I did not yet track this down.  Maybe you have some idea what's up?
```sh
 file copy failed: cannot stat ‘/cache/home/mt652/am/facts/modules/fair/temperature/data/fair_temperature_preprocess_data.tgz'
 file copy failed: cannot stat ‘/cache/home/mt652/am/facts/modules/fair/temperature/data/fair_temperature_fit_data.tgz'
 file copy failed: cannot stat ‘/cache/home/mt652/am/facts/modules/kopp14/verticallandmotion/data/bkgdrate.tsv'
 file copy failed: cannot stat ‘/cache/home/mt652/am/facts/modules/total/total_workflow.py'
 file copy failed: cannot stat ‘/cache/home/mt652/am/facts/modules/extremesealevel/pointsoverthreshold/data/extremesealevel_pointsoverthreshold_data.tgz'
```

The instructions above are a bit terse, apologies - we will write up a more detailed documentation once the deployment is a bit more streamlined...

**Comment by bobkopp** [comment]
Ok, just to check I did this from scratch again:

```
$ conda create -n facts
$ conda activate facts
$ conda install -c conda-forge radical.entk
$ conda install numpy scipy netCDF4 pyyaml matplotlib h5py yq
$ git clone git@github.com:radical-collaboration/facts.git
$ cd facts/modules-data
$ ln -s /projects/kopp/facts-dev/modules-data/*.tgz .
$ cd ..
$ mkdir test
$ cp -r experiments/temp_exp test
$ emacs test/config.yml
  -> replace 'localhost' with 'amarel'
$ python runFACTS.py test
```

and I get:

```
EnTK session: re.session.amarel1.amarel.rutgers.edu.rk509.019299.0002
Creating AppManagerSetting up RabbitMQ system                                 ok
                                                                              ok
Validating and assigning resource manager                                     ok
Setting up RabbitMQ system                                                   n/a
new session: [re.session.amarel1.amarel.rutgers.edu.rk509.019299.0002]All components terminated
Traceback (most recent call last):
  File "/home/rk509/anaconda3/envs/facts/lib/python3.9/site-packages/radical/entk/execman/rp/resource_manager.py", line 157, in submit_resource_request
    self._session = rp.Session(uid=self._sid)
  File "/home/rk509/anaconda3/envs/facts/lib/python3.9/site-packages/radical/pilot/session.py", line 154, in __init__
    self._initialize_primary(dburl)
  File "/home/rk509/anaconda3/envs/facts/lib/python3.9/site-packages/radical/pilot/session.py", line 168, in _initialize_primary
    if not dburl: raise RuntimeError("no db URL (set RADICAL_PILOT_DBURL)")
RuntimeError: no db URL (set RADICAL_PILOT_DBURL)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/rk509/anaconda3/envs/facts/lib/python3.9/site-packages/radical/entk/appman/appmanager.py", line 445, in run
    self._rmgr.submit_resource_request()
  File "/home/rk509/anaconda3/envs/facts/lib/python3.9/site-packages/radical/entk/execman/rp/resource_manager.py", line 220, in submit_resource_request
    raise EnTKError(ex) from ex
radical.entk.exceptions.EnTKError: no db URL (set RADICAL_PILOT_DBURL)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/cache/home/rk509/facts/runFACTS.py", line 123, in <module>
    run_experiment(args.edir, args.debug)
  File "/cache/home/rk509/facts/runFACTS.py", line 65, in run_experiment
    amgr.run()
  File "/home/rk509/anaconda3/envs/facts/lib/python3.9/site-packages/radical/entk/appman/appmanager.py", line 476, in run
    raise ree.EnTKError(ex) from ex
radical.entk.exceptions.EnTKError: no db URL (set RADICAL_PILOT_DBURL)
```

**Comment by andre-merzky** [comment]
Conda should make no difference.  Thanks for providing the steps, I'll try to reproduce your setup.

**Comment by bobkopp** [comment]
Now running!
